jobs:
  include:
  - stage: build
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u avtandilko --password-stdin
    - docker build -t avtandilko/jekyll:$TRAVIS_BUILD_NUMBER .
    - docker push avtandilko/jekyll:$TRAVIS_BUILD_NUMBER
env:
  global:
    secure: A69TPLyNzpQEY2zPWE9XGlKMiHDPoRqHaWLpoLG2fG7TQwnl+OdT81opDbnVTQluAR0ex6K3uNLdlPMN6d7FMCvM2ZN6kx+5+0e8X1T7jlqTc0EXKj3BszgRAehT8OR4ts93NGbH0x8ua9QJQ9iOLqBQE5cSyA8vU/h+YME7oME8b3zrAeAAwIwLgT30lhKqn3NztLVpGTN1GgZi18+Sue2zkb5rLOz7ucpP+pexBX+j+Puy9BZC2IKiigygCwPjpCrrzXQCuiWM4JWinJDeGOX6J3cQ02GoTz+SzNJqohMp92v9BbTeyXP0hUhGk4hAKowGAm+7CVo1TQniicTOeW5yuS4roC6cHkgMXAGgLQbusDC/rojOtyCnd1cEWra/0wugl4JcBJRdCr3ev1ycuZSWAwMmvhXJeDPOO53VKK+45jUoZL0Ijr/AtULM0d5Uns3dQYBaHrhQH/QFLWEWVsHjcgCnAhPtPXOQQQFs7k7rdujjHMtce1FDJY7aw21vLEjOU8p4RxWH4xxi4FKOEmDvytbBSncnhO+Ciws+EnVmh29+dogtjsodFk6tUNjsSCSsjtuTpO+IXkjwlk1ePlC1hhPGaIErF/S9S//Z6rjYb53TWUmIpA0ekp5NRPf9a3IUxhL7C5ZGH5kcOxd3/kfPoyFwLidQ+m9pbZ6gQZs=
