# Dependencies
markdown:         kramdown
highlighters:     true

# Permalinks
permalink:        pretty

# Setup
title:            AboutNet
tagline:          'all about networks'

paginate:         5

url: https://aboutnet.net

plugins: 
  - jekyll-paginate
  - jekyll-read-more
